
add_requires("cryptopp")
add_requires("cpp-httplib")
add_requires("nlohmann_json")
-- add_requires("mysql")

target("SafeChat")
    set_kind("binary")
    add_files("./src/main.cpp")
    add_files("./src/Server/**.cpp")
    add_files("./src/Config/**.cpp")
    add_files("./src/Token/**.cpp")
    add_files("./src/Entity/**.cpp")
    add_files("./src/Utils/**.cpp")
    add_files("./src/Test/**.cpp")
    add_packages("cryptopp")
    add_packages("cpp-httplib")
    add_packages("nlohmann_json")
    -- add_packages("mysql")
